### PR TITLE
Enabling the reuse of a MongoClient

### PR DESCRIPTION
**Pull request by algomaks**
## Purpose
The main idea is to enable the reusing of a MongoClient between this module and the rest of the Node.js application. For this purpose, I have added an additional parameter called "client" to the MongoDbStorageConfig of the MongoDbStorage class.

There will be two main ways to use the module:
1. Provide the url, database and collection in the config - the AS IS case.
2. Provide a client, database and collection in the config - the NEW case.  

Please notice that url is now an optional parameter.

## Does this introduce a breaking change?

```
[ ] Yes
[ x] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other - Please describe:
            _______________
```

### CODE REVIEW

**Comment by hattan** [comment]
Thanks @algomax ! That's a really interesting addition to the project. Would you be able to add tests covering the changes including this check for either client or url?
https://github.com/algomax/botbuilder-storage-mongodb/blob/mongo_client/src/MongoDbStorage.ts#L51

You can see the current code coverage by expanding the unit tests section here.
https://dev.azure.com/BotBuilderPackages/mongoDBStorage/_build/results?buildId=71

Thanks!

**Comment by algomax** [comment]
Hi @hattan,

Thank you for the feedback and for maintaining this awesome project.

I might add some tests, but I am not sure if I will have the time for this soon.

Regards!

**Comment by laeckerv** [comment]
@hattan does this PR only need additional tests to cover the new use case?

I could add those, if that means this PR gets merged.

**Comment by nurih** [comment]
This PR was held off due to test coverage and structure issues. But the idea is both sound and desirable. 
There's a pending PR for @hattan to review which restructures the code. After that , I was planning to introduce the client as a fully connected and constructed dependency only, removing the notion of `connect` from the main class altogether.

**Comment by hattan** [comment]
@nurih - pending restructure PR has been approved and merged, please proceed with your changes. Thanks!

**Comment by anotheri** [comment]
any update on merging this?

**Pull request closed without merging**
